### ISSUE TITLE
Multiple cameras have the same cameraID

### ISSUE THREAD

**Issue by LenaKM** [ddietze/Py-Hardware-Support#2]
This means I can't use `connect()` to access different cameras.

Output:
```
API version 4.80.5
Found 2 camera(s)
Camera #0: SerNo = b'____657006', CameraID = 1, DeviceID = 3
Camera #1: SerNo = b'____046827', CameraID = 1, DeviceID = 1
```

Is there a way to connect using `DeviceID` or serial number?

**Comment by ddietze** [comment]
Hi Lena,

I have changed `connect()` to allow connecting to cameras using both cameraID or deviceID. 
In principle, it should work like

    cam1 = uc480.uc480()
    cam2 = uc480.uc480()
    cam1.connect(3, useDevID=True)
    cam2.connect(1, useDevID=True)

Unfortunately, I have no possibility to test my changes as I don't have access to an uc480 camera any more. It would be great if you would try it and could give me a short feedback.

Alternatively, the cameraID seems to be stored in the camera, according to the uc480 manual.
It can be set by the user through the software delivered with the camera. The deviceID on the other hand is set anew every time the computer reboots.

Hope this helps!
Cheers, 
Daniel

**Comment by LenaKM** [comment]
I get the following error:

```
File "C:/Users/Lena/Dropbox/pythonscripts/camera_test.py", line 21, in <module>
    cam.connect(1, useDevID=True)

File "C:\Users\Lena\pythonscripts\uc480\__init__.py", line 211, in connect
    self._camID = HCAM(cameraID) if not useDevID else HCAM(cameraID | IS_USE_DEVICE_ID)

NameError: name 'cameraID' is not defined
```

I'll have a look at how to set the camera ID, as this should solve my issue.


Cheers

**Comment by LenaKM** [comment]
FYI The old way also now raises this error with the updated __init__.py file:

```
  File "C:/Users/Lena/Dropbox/pythonscripts/camera_test.py", line 25, in <module>
    cam.connect(cameraID=0)

TypeError: connect() got an unexpected keyword argument 'cameraID'
```

**Comment by ddietze** [comment]
Hi Lena, 
sorry for that typo - it has to read `ID` instead of `cameraID` in `connect()`. I have just corrected the file.
Now it should hopefully work ;)
Cheers, Daniel

**Comment by LenaKM** [comment]
I get this error:

```
  File "C:/Users/Lena/Dropbox/pythonscripts/camera_test.py", line 29, in <module>
    cam1.connect(1, useDevID=True)

  File "C:\Users\Lena\Dropbox\pythonscripts\uc480\__init__.py", line 212, in connect
    self.call("is_InitCamera", ptr(self._camID), None)

  File "C:\Users\Lena\Dropbox\pythonscripts\uc480\__init__.py", line 116, in call
    assrt(func(*args), function)

  File "C:\Users\Lena\Dropbox\pythonscripts\uc480\__init__.py", line 66, in assrt
    raise uc480Error(retVal, "Error: uc480 function call failed! Error code = " + str(retVal), fname)

uc480Error: Error: uc480 function call failed! Error code = 3 in function is_InitCamera
```

with the code

```
import uc480
import pylab as pl

# create instance and connect to library
cam1 = uc480.uc480()


cam1.connect(1, useDevID=True)

# take a single image
img1 = cam1.acquire()


# clean up
cam1.disconnect()


pl.imshow(img1)
pl.show()
```

and the error

 ```
 File "C:/Users/Lena/Dropbox/pythonscripts/camera_test.py", line 28, in <module>
    cam1.connect(ID=1)

  File "C:\Users\Lena\Dropbox\pythonscripts\uc480\__init__.py", line 212, in connect
    self.call("is_InitCamera", ptr(self._camID), None)

  File "C:\Users\Lena\Dropbox\pythonscripts\uc480\__init__.py", line 116, in call
    assrt(func(*args), function)

  File "C:\Users\Lena\Dropbox\pythonscripts\uc480\__init__.py", line 66, in assrt
    raise uc480Error(retVal, "Error: uc480 function call failed! Error code = " + str(retVal), fname)

uc480Error: Error: uc480 function call failed! Error code = 3 in function is_InitCamera
```
using `cam1.connect(ID=1)` instead.


Thanks for all the help.

**Comment by ddietze** [comment]
Hi Lena,
have you tried the code with just one camera attached? 
Also, does calling `connect()` without arguments connect to the camera?
Sorry that I cannot debug the code myself.
Cheers, Daniel

**Comment by LenaKM** [comment]
Using connect() without arguments works as before, having only one camera attached makes no difference. Still get a `uc480Error: Error: uc480 function call failed! Error code = 3 in function is_InitCamera` error when trying to use an identifier.

I managed to change the camera IDs using the camera manager program that comes with thorcam, but this still doesn't let me identify different cameras in the old code, it just seems to use the 'first available' camera.

Cheers

**Comment by ddietze** [comment]
As a workaround, you might try calling `connect()` twice without identifier. In the manual it says that it will connect to the **next available** camera, i.e.

    cam1 = uc480.uc480()
    cam2 = uc480.uc480()
    cam1.connect()
    cam2.connect()

should connect to camera 1 and 2.
Maybe it works. 

I fear that other than this I cannot provide a quick solution at the moment. I will delve into this topic tonight when I have more time.. 
Cheers, Daniel

**Comment by LenaKM** [comment]
This was the next thing I tried, and it appears to work this way. It for some reason needs a short delay between image captures to work properly on both cameras, otherwise one or both images are very dark or look like static even with the exposure time set.


Thanks for the help!

**Comment by kaibui** [comment]
Hi, I am trying to utilize cameras as well using this, however, I've been getting similar error messages, however, I also get the `Error: uc480 function call failed! Error code = 155 in function is_Blacklevel`, when I try to cam.connect(). I went into __init__ and commented out the Blacklevel portion of connect(), I received no error.

I was able to acquire an image by doing this, however, as stated by LenaKM, the image is very static, column-like noise. I tried to set Blacklevel but nothing seems to happen.

I was wondering if you had any other insights or suggestions.
Thank you.
